//Sex 20 Dez 2019 21:15:30 -03 
typedef enum err_t {
   PyC_ERR_OK=0,
   PyC_ERR_BUFFER_ALLOC,
   PyC_ERR_CANT_PARSE_TUPLE_AND_KEYWORDS,
   PyC_ERR_NULL_BUFFER,
   PyC_ERR_MEM_OVFL,
   PyC_ERR_STRUCT_UNDEF,
   PyC_ERR_RAW_DATA_SZ_ZERO,
   PyC_ERR_DATA_OBJ_NOT_READY,
   PyC_ERR_DATA_OBJ_CREATE,
   PyC_ERR_DATA_OBJ_CREATE_ATTR,
   PyC_ERR_ADD_METHOD,
   PyC_ERR_NULL_OBJ,
   PyC_ERR_PUBLISH_ADDR_OVFL,
   PyC_ERR_F_NANO_TRANSACTION_RAW_DATA_SZ_MAX_OVF,
   PyC_ERR_CANT_OPEN_FILE,
   PyC_ERR_READING_FILE

} FPYC_ERR;

#define MSG_ERR_CANT_PARSE_TUPLE_AND_KEYWDS "\nCannot parse tuple and keywords to C library\n"
#define MSG_ERR_ALLOC_BUFFER "\nCannot alloc buffer \"FIOT_RAW_DATA_OBJ\"\n"
